# NodeJS Version 16
FROM node:lts-alpine3.20

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

RUN npm install -g pnpm
# Install Node Package
RUN pnpm install

# Set Env
ENV NODE_ENV development
EXPOSE 3000

# Cmd script
CMD ["pnpm", "run", "dev"]
