# baseURL
@baseURL = http://localhost:5000

###
# Find All Properties
GET {{ baseURL }}/property?page_number=1&page_size=10

###
GET {{ baseURL }}/property/islamabad?page_number=1000&page_size=10

###
# Find property By Id
GET {{ baseURL }}/property/3

###
GET {{ baseURL }}/property/count
